### ISSUE TITLE
Question: assets seems to be missing

### ISSUE THREAD

**Issue by uffejakobsen** [hayesmaker/thrust-platform#57]
Question: assets seems to be missing

Context:
cloned repo - HEAD @ commit 84dd2e79c5f17214c028add328b6ac18dcf0f8ab
running bin/www
start browser @ localhost:4000

Problem: I get these 404's which seems to break game startup

GET /assets/audiosprite/thrust-sfx.mp3 404 39.533 ms - 3206
GET /assets/audiosprite/thrust-sfx.json 404 40.372 ms - 3206
GET /assets/audiosprite/thrust-music.mp3 404 72.239 ms - 3206
GET /assets/audiosprite/thrust-music.json 404 114.584 ms - 3206
GET /assets/atlas/combined.png 404 28.180 ms - 3206

Question: Is something missing from the repo ?

**Comment by hayesmaker** [comment]
Hi there, 

All the current game assets are under non open source licence, so you will either have to supply your own sound and graphics assets, or wait for me to add place holders to the repo.

**Comment by hayesmaker** [comment]
Demo assets are now included in the source repo. Follow the steps in readme to build the entire game (Mission 1 only)
